---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marsroverapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: marsroverapi
    spec:
      containers:
      - name: marsroverapi
        image: acrcontosovideo.azurecr.io/marsroverapi/marsroverapi:latest
        ports:
        - containerPort: 8080
        resources:
            requests: # Minimum amount of resources requested
              cpu: 100m
              memory: 128Mi
            limits: # Maximum amount of resources requested
              cpu: 250m
              memory: 256Mi
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 5
          initialDelaySeconds: 3
          periodSeconds: 3
  selector:
    matchLabels:
      app: marsroverapi
---
apiVersion: v1
kind: Service
metadata:
  name: marsroverapi
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: marsroverapi
  type: LoadBalancer